### ISSUE TITLE
 red theme color not available

### ISSUE THREAD

**Issue by pippo92** [ordovice/es-theme-next-level-remix#1]
Hi I downloaded this fantastic theme but every time I try to set the color of the red theme from the menu it always remains blue why?

**Comment by ordovice** [comment]
That's legacy code from a prior version.  One of the items I need to remove or finish re-implementing.

**Comment by pippo92** [comment]
I'm sorry but I don't understand well I am Italian and I am writing to you via translator, so you have not yet implemented this function?

**Comment by ordovice** [comment]
Correct.  It was framework from another theme that I haven't finished implementing, as the blue is actually created by the graphics.  Technically the red is only changing the menu text colors at this time.

**Comment by pippo92** [comment]
I understand, so are you going to implement it or remove it? if you intend to implement it when you insert it?

**Comment by ordovice** [comment]
Look for this issue to be closed with whatever I decide to do :-).  I won't close it until then.  If you're using Batocera, then you'll be able to just re-download the theme again and restart to see the changes.

**Comment by pippo92** [comment]
Look I'm not telling you what you should or shouldn't do. I just wanted to have more information, because if you didn't intend to implement it I would change the theme here.

**Comment by ordovice** [comment]
It will depend on my time commitments.  I'm thinking I will be implementing it, but not certain at the moment as I have a few other tasks higher in the queue.

**Comment by pippo92** [comment]
OK thanks

**Comment by ordovice** [comment]
Halos are now showing the correct color in relation to the color picked.  If you re-download via theme downloader it is available now.  Working on some other areas where color needs an update.

**Comment by ordovice** [comment]
I've also added color to the gamelist view screens.
